---
:concurrency: 5
:timeout: 25
:verbose: false
:queues:
  - default
  - mailers
  - low_priority

:schedule:
  schedule_appointment_reminders:
    cron: '0 * * * *' # Every hour at minute 0
    class: ScheduleAppointmentRemindersJob

development:
  :concurrency: 3

production:
  :concurrency: 10

staging:
  :concurrency: 5
